::  Tests for Saloon HERMITIAN eigendecomposition (+eig on %cplx).
::
::  GENERATED by saloon/tools/eigh_check.py -- do not edit by hand.
::  Per matrix: sort(computed real eigenvalues) = sort(eigh).
::  @cs (bloq 6) uses single-precision components, so a looser tol;
::  @cd (bloq 7) uses double.  Oracle: numpy.linalg.eigvalsh.
::
/-  ls=lagoon
/+  *test, *saloon, *lagoon
|%
::  cs single-precision saloon (rtol must be @rs-width); cd double.
++  scs  (sake %n .1e-6)
++  scd  (sake %n .~1e-12)
++  closes
  |=  [x=ray:ls y=ray:ls]
  ^-  ?
  (all:(lake %n) (is-close:(lake %n) x y [.1e-4 .1e-4]))
++  closed
  |=  [x=ray:ls y=ray:ls]
  ^-  ?
  (all:(lake %n) (is-close:(lake %n) x y [.~1e-9 .~1e-9]))
++  sortr
  |=  [r=ray:ls n=@ b=@]
  ^-  ray:ls
  =/  lst=(list @)
    =/  i  0
    =/  acc=(list @)  ~
    |-  ^-  (list @)
    ?:  =(i n)  (flop acc)
    $(i +(i), acc [(get-item:(lake %n) r ~[i]) acc])
  =/  cmp
    ?:  =(6 b)  |=([p=@ q=@] (~(lth rd:math [%n .~1e-10]) p q))
    |=([p=@ q=@] (~(lth rs:math [%n .1e-6]) p q))
  (en-ray:(lake %n) [[~[n] b %i754 ~] (sort lst cmp)])
::  cs2: 2x2 Hermitian, eigenvalues [1.0, 3.0]
++  m-cs2
  ^-  ray:ls
  (en-ray:(lake %n) [[~[2 2] 6 %cplx ~] ~[~[0x4000.0000 0x3f80.0000.0000.0000] ~[0xbf80.0000.0000.0000 0x4000.0000]]])
++  w-cs2
  ^-  ray:ls
  (en-ray:(lake %n) [[~[2] 5 %i754 ~] ~[.1.0 .3.0]])
++  test-cs2
  %-  expect
  !>  (closes (sortr (eigvals:scs m-cs2) 2 5) w-cs2)
::  cs3: 3x3 Hermitian, eigenvalues [-1.65598, -0.87975, 1.42205]
++  m-cs3
  ^-  ray:ls
  (en-ray:(lake %n) [[~[3 3] 6 %cplx ~] ~[~[0x3e00.bf6c 0x3f59.d327.bc5e.dc7d 0x3ec6.0a36.3f78.e2d8] ~[0xbf59.d327.bc5e.dc7d 0xbf09.21a1 0xbeb3.9f77.3f27.82b2] ~[0xbec6.0a36.3f78.e2d8 0x3eb3.9f77.3f27.82b2 0xbf34.27fe]]])
++  w-cs3
  ^-  ray:ls
  (en-ray:(lake %n) [[~[3] 5 %i754 ~] ~[.-1.6559778798437097 .-0.8797453878109185 .1.4220488797799182]])
++  test-cs3
  %-  expect
  !>  (closes (sortr (eigvals:scs m-cs3) 3 5) w-cs3)
::  cs4: 4x4 Hermitian, eigenvalues [-2.01198, -0.96021, 1.63983, 2.75159]
++  m-cs4
  ^-  ray:ls
  (en-ray:(lake %n) [[~[4 4] 6 %cplx ~] ~[~[0x3eb0.f069 0xbe19.e81a.3f5d.0d7c 0x3f76.f1cc.3eb1.ec24 0xbe71.1151.bf82.88fe] ~[0x3e19.e81a.3f5d.0d7c 0x3ee4.8b35 0x3fcb.b789.bdf8.a600 0x3eca.1646.3e56.1f61] ~[0xbf76.f1cc.3eb1.ec24 0xbfcb.b789.bdf8.a600 0x3ce8.d5c3 0xbfa2.8fd6.3d04.49b0] ~[0x3e71.1151.bf82.88fe 0xbeca.1646.3e56.1f61 0x3fa2.8fd6.3d04.49b0 0x3f19.4dfc]]])
++  w-cs4
  ^-  ray:ls
  (en-ray:(lake %n) [[~[4] 5 %i754 ~] ~[.-2.0119794408981573 .-0.9602106763203604 .1.6398302476267073 .2.7515870879710316]])
++  test-cs4
  %-  expect
  !>  (closes (sortr (eigvals:scs m-cs4) 4 5) w-cs4)
::  cd3: 3x3 Hermitian, eigenvalues [-0.93746, 0.06811, 3.13932]
++  m-cd3
  ^-  ray:ls
  (en-ray:(lake %n) [[~[3 3] 7 %cplx ~] ~[~[0x3fc8.32e6.b600.2ebd 0x3fe4.e6fa.9f24.ada4.bff7.b6b6.c937.11c6 0xbfbb.0dcb.8fc0.da40.bfd7.a1ae.3078.3897] ~[0xbfe4.e6fa.9f24.ada4.bff7.b6b6.c937.11c6 0x3ffc.cb99.f7f2.7f19 0xbfa7.1fe8.b453.5394.3fee.b003.e390.61f2] ~[0x3fbb.0dcb.8fc0.da40.bfd7.a1ae.3078.3897 0x3fa7.1fe8.b453.5394.3fee.b003.e390.61f2 0x3fd1.ff5b.0984.4c53]]])
++  w-cd3
  ^-  ray:ls
  (en-ray:(lake %n) [[~[3] 6 %i754 ~] ~[.~-0.937458527529203 .~0.06811111121050753 .~3.1393188506307803]])
++  test-cd3
  %-  expect
  !>  (closed (sortr (eigvals:scd m-cd3) 3 6) w-cd3)
::  cd4: 4x4 Hermitian, eigenvalues [-1.70954, -0.73939, 1.12023, 2.98901]
++  m-cd4
  ^-  ray:ls
  (en-ray:(lake %n) [[~[4 4] 7 %cplx ~] ~[~[0x4000.53cd.6781.0b16 0xbfc0.d1ee.564c.798d.bff8.1107.1999.93bf 0x3fe2.3fe3.59b0.0c56.bfcc.9d85.005f.5a61 0x3f96.6742.2e94.4404.bfdb.2b79.a2f6.fea9] ~[0x3fc0.d1ee.564c.798d.bff8.1107.1999.93bf 0xbfcb.98b0.164a.5bae 0x3f62.c2e3.5426.b880.3fe4.d924.90d8.d70e 0xbfe8.1ee4.b6a4.6d6e.bfdc.cca0.2e33.b29c] ~[0xbfe2.3fe3.59b0.0c56.bfcc.9d85.005f.5a61 0xbf62.c2e3.5426.b880.3fe4.d924.90d8.d70e 0x3fcc.e693.63d8.2196 0x3fd3.bd26.6f1a.3064.bfe6.8645.bb70.ac21] ~[0xbf96.6742.2e94.4404.bfdb.2b79.a2f6.fea9 0x3fe8.1ee4.b6a4.6d6e.bfdc.cca0.2e33.b29c 0xbfd3.bd26.6f1a.3064.bfe6.8645.bb70.ac21 0xbfd9.02e2.1a1d.ee83]]])
++  w-cd4
  ^-  ray:ls
  (en-ray:(lake %n) [[~[4] 6 %i754 ~] ~[.~-1.7095387529584372 .~-0.7393939278917311 .~1.1202312348359966 .~2.9890090403028555]])
++  test-cd4
  %-  expect
  !>  (closed (sortr (eigvals:scd m-cd4) 4 6) w-cd4)
--
