#!/usr/bin/env python3
"""Generate hoon/float-tests.hoon: per (door, op, value set, mode) rows that
exercise hoon-138's rh/rs/rd/rq doors. Each row returns ~; under
NOCK_TEST_JETS every arm call is checked against the Nock, so a mismatch is
a %jest crash of that row. "safe" values cannot overflow; "big" adds the
ones that can (max, subnormals, min normal), which under %u/%d/%z hit the
Hoon's overflow-to-infinity divergence (urbit/urbit#7426).

  scripts/gen-float-tests.py && (cd hoon && hoonc --arbitrary --output float-tests.jam float-tests.hoon .)
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_float_values import doors
out=['::  generated by scripts/gen-float-tests.py; do not edit',
     '::  per (door, op, value set, mode) rows for the float-door jets; each row',
     '::  returns ~. Under NOCK_TEST_JETS a mismatch is a %jest crash.',
     '::  "safe" values cannot overflow; "big" ones can (max, subnormals, ...).',
     '|.','^-  (list [@t (trap (list @t))])',':~']
for d,(aura,safe,big) in doors.items():
    for setname,vals in (('safe',safe),('big',safe+big)):
        lit=' '.join(f'`{aura}`{v}' for v in vals)
        for m in ('n','u','d','z'):
            for op in ('add','sub','mul','div','sqt','lth','lte','equ','gte','gth'):
                out.append(f"  :-  '{d}/{op}/{setname}/{m}'")
                out.append(f"  |.  ^-  (list @t)")
                out.append(f"  =/  vs  `(list {aura})`~[{lit}]")
                if op=='sqt':
                    out.append(f"  =/  r  (turn vs |=(a={aura} (~(sqt {d} %{m}) a)))")
                else:
                    out.append(f"  =/  r  (turn vs |=(a={aura} (turn vs |=(b={aura} (~({op} {d} %{m}) a b)))))")
                out.append(f"  ?~(r ~ ~)")
out.append('==')
path=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..','hoon','float-tests.hoon')
open(path,'w').write('\n'.join(out)+'\n')
print(sum(1 for l in out if l.startswith("  :-")),'rows ->',os.path.normpath(path))
