#!/bin/sh
# Copy the lagoon Hoon (lib, sur, tests) into hoon/ for hoonc, rewriting the
# jet parent `..part` (Arvo) to `..ut` (bare hoon-138), and generate the test
# runner trap. Re-run after any change to the desk sources.
set -eu
cd "$(dirname "$0")/.."
N=../..                      # numerics repo root
rm -rf hoon/lib hoon/sur hoon/run-tests.hoon hoon/run-tests.jam hoon/.jam-ok && mkdir -p hoon/lib hoon/sur
cp $N/lagoon/desk/sur/lagoon.hoon hoon/sur/
cp $N/lagoon/desk/lib/lagoon.hoon hoon/lib/
for f in twoc unum complex fixed; do cp $N/libmath/desk/lib/$f.hoon hoon/lib/; done
cp $N/zod/base/lib/test.hoon hoon/lib/
cp $N/lagoon/desk/tests/lib/lagoon-*.hoon hoon/lib/
sed -i '' 's/\.\.part/..ut/' hoon/lib/*.hoon
# runner (only lib/, sur/, run-tests.hoon are regenerated; other files in hoon/ are left alone)
{
  printf '::  generated by scripts/sync-hoon.sh; do not edit\n'
  i=0
  for f in $N/lagoon/desk/tests/lib/lagoon-*.hoon; do
    b=$(basename "$f" .hoon); i=$((i+1))
    printf '/+  t%s=%s\n' "$i" "$b"
  done
  printf '|.\n^-  (list [@t (trap (list @t))])\n=/  ren  |=(t=tang (turn t |=(k=tank (crip ~(ram re k)))))\n:~\n'
  i=0
  for f in $N/lagoon/desk/tests/lib/lagoon-*.hoon; do
    b=$(basename "$f" .hoon); i=$((i+1))
    grep -o '^++  test-[a-z0-9-]*' "$f" | sed 's/^++  //' | while read -r arm; do
      printf "  ['%s/%s' |.((ren %s:t%s))]\n" "$b" "$arm" "$arm" "$i"
    done
  done
  printf '==\n'
} > hoon/run-tests.hoon
echo "synced: $(ls hoon/lib | wc -l | tr -d ' ') lib files, $(grep -c "^  \['" hoon/run-tests.hoon) tests"
