#!/usr/bin/env python3
"""Oracle + Hoon emitter for Saloon symmetric-Jacobi eigendecomposition (+eig).

Generates a catalogue of standard symmetric test matrices and their reference
spectra (numpy.linalg.eigh), then prints a complete /tests/lib/saloon-eig.hoon
whose cases check, per matrix:

  * eigpair:  A * V  ==  V * diag(eigenvalues)   (order/sign independent)
  * spectrum: sort(computed eigenvalues) == sort(eigh eigenvalues)

All values are emitted as f64 (@rd, bloq 6) Hoon float literals.

Catalogue (the four standard sources):
  closed-form  : 1-D Laplacian tridiag(2,-1) -- analytic spectrum 2-2cos(k.pi/(n+1))
  torture      : Rosser 8x8, Wilkinson W7+, Pascal 4, Hilbert 4
  real-world   : cycle-graph C5 Laplacian, covariance/Gram M^T M
  random SPD   : seeded A = M^T M
"""

import math

import numpy as np


def hoon_float(x: float) -> str:
    """Round-trippable Hoon @rd literal, e.g. .~2.0 / .~1e-9 (no leading-zero exp)."""
    x = float(x)
    if x == 0.0:
        return ".~0"
    s = repr(x)
    if "e" in s or "E" in s:
        mant, exp = s.lower().split("e")
        sign = ""
        if exp[0] in "+-":
            sign, exp = ("-" if exp[0] == "-" else ""), exp[1:]
        exp = exp.lstrip("0") or "0"
        s = f"{mant}e{sign}{exp}"
    return f".~{s}"


def ndray(mat: np.ndarray) -> str:
    """A 2-D matrix as a Hoon ndray literal: ~[~[a b] ~[c d]]."""
    rows = ["~[" + " ".join(hoon_float(v) for v in row) + "]" for row in mat]
    return "~[" + " ".join(rows) + "]"


def vlist(vec) -> str:
    """A 1-D vector as a Hoon list literal: ~[a b c]."""
    return "~[" + " ".join(hoon_float(v) for v in vec) + "]"


# ---------------------------------------------------------------------------
# matrix catalogue
# ---------------------------------------------------------------------------

def laplacian_1d(n):
    a = 2 * np.eye(n) - np.eye(n, k=1) - np.eye(n, k=-1)
    return a


def rosser():
    return np.array([
        [611, 196, -192, 407, -8, -52, -49, 29],
        [196, 899, 113, -192, -71, -43, -8, -44],
        [-192, 113, 899, 196, 61, 49, 8, 52],
        [407, -192, 196, 611, 8, 44, 59, -23],
        [-8, -71, 61, 8, 411, -599, 208, 208],
        [-52, -43, 49, 44, -599, 411, 208, 208],
        [-49, -8, 8, 59, 208, 208, 99, -911],
        [29, -44, 52, -23, 208, 208, -911, 99],
    ], dtype=float)


def wilkinson_plus(n):
    # n must be odd; diagonal |(n-1)/2 - i|, off-diagonal 1.
    m = (n - 1) // 2
    diag = np.array([abs(m - i) for i in range(n)], dtype=float)
    a = np.diag(diag) + np.eye(n, k=1) + np.eye(n, k=-1)
    return a


def pascal_sym(n):
    a = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            a[i, j] = math.comb(i + j, i)
    return a


def hilbert(n):
    return np.array([[1.0 / (i + j + 1) for j in range(n)] for i in range(n)])


def cycle_laplacian(n):
    a = 2 * np.eye(n) - np.eye(n, k=1) - np.eye(n, k=-1)
    a[0, n - 1] = a[n - 1, 0] = -1.0
    return a


def gram(seed, k, n):
    rng = np.random.default_rng(seed)
    m = rng.standard_normal((k, n))
    return m.T @ m


def random_spd(seed, n):
    rng = np.random.default_rng(seed)
    m = rng.standard_normal((n, n))
    return m @ m.T


CASES = [
    ("laplacian5", laplacian_1d(5)),
    ("rosser8", rosser()),
    ("wilkinson7", wilkinson_plus(7)),
    ("pascal4", pascal_sym(4)),
    ("hilbert4", hilbert(4)),
    ("cycle5", cycle_laplacian(5)),
    ("gram4", gram(0, 6, 4)),
    ("spd5", random_spd(1, 5)),
    ("spd6", random_spd(2, 6)),
]


def emit_hoon():
    print("::  Tests for Saloon symmetric-Jacobi eigendecomposition (+eig).")
    print("::")
    print("::  GENERATED by saloon/tools/eig_check.py -- do not edit by hand.")
    print("::  Per matrix: A*V = V*diag(vals) (eigpair, order/sign free) and")
    print("::  sort(computed vals) = sort(eigh vals).  Oracle: numpy.linalg.eigh.")
    print("::")
    print("/-  ls=lagoon")
    print("/+  *test, *saloon, *lagoon")
    print("|%")
    print("++  sad  (sake %n .~1e-12)")
    print("::  closeness with absolute + relative floor sized for ~1e3 magnitudes.")
    print("++  close")
    print("  |=  [x=ray:ls y=ray:ls]")
    print("  ^-  ?")
    print("  (all:(lake %n) (is-close:(lake %n) x y [.~1e-6 .~1e-6]))")
    print("++  mk-diag")
    print("  |=  [vals=ray:ls n=@]")
    print("  ^-  ray:ls")
    print("  =/  z  (zeros:(lake %n) [~[n n] 6 %i754 ~])")
    print("  =/  i  0")
    print("  |-  ^-  ray:ls")
    print("  ?:  =(i n)  z")
    print("  =.  z  (set-item:(lake %n) z ~[i i] (get-item:(lake %n) vals ~[i]))")
    print("  $(i +(i))")
    print("::  ascending-sorted copy of a 1-D eigenvalue ray (Jacobi order is arbitrary).")
    print("++  sorted")
    print("  |=  [r=ray:ls n=@]")
    print("  ^-  ray:ls")
    print("  =/  lst=(list @)")
    print("    =/  i  0")
    print("    =/  acc=(list @)  ~")
    print("    |-  ^-  (list @)")
    print("    ?:  =(i n)  (flop acc)")
    print("    $(i +(i), acc [(get-item:(lake %n) r ~[i]) acc])")
    print("  =/  srt  (sort lst |=([p=@ q=@] (~(lth rd:math [%n .~1e-10]) p q)))")
    print("  (en-ray:(lake %n) [[~[n] 6 %i754 ~] srt])")
    print("++  eigpair-ok")
    print("  |=  [a=ray:ls n=@]")
    print("  ^-  ?")
    print("  =/  res  (eig:sad a)")
    print("  =/  av   (mmul:(lake %n) a vecs.res)")
    print("  =/  vd   (mmul:(lake %n) vecs.res (mk-diag vals.res n))")
    print("  (close av vd)")
    print("++  spectrum-ok")
    print("  |=  [a=ray:ls n=@ want=ray:ls]")
    print("  ^-  ?")
    print("  (close (sorted vals:(eig:sad a) n) want)")
    for name, mat in CASES:
        n = mat.shape[0]
        w = np.linalg.eigvalsh(mat)
        w = np.sort(w)
        print(f"::  {name}: {n}x{n}, eigenvalues {[round(float(v),6) for v in w]}")
        print(f"++  m-{name}")
        print(f"  (en-ray:(lake %n) [[~[{n} {n}] 6 %i754 ~] {ndray(mat)}])")
        print(f"++  w-{name}")
        print(f"  (en-ray:(lake %n) [[~[{n}] 6 %i754 ~] {vlist(w)}])")
        print(f"++  test-eigpair-{name}   (expect !>((eigpair-ok m-{name} {n})))")
        print(f"++  test-spectrum-{name}  (expect !>((spectrum-ok m-{name} {n} w-{name})))")
    print("--")


if __name__ == "__main__":
    emit_hoon()
