#!/usr/bin/env python3
"""Oracle + Hoon emitter for Saloon HERMITIAN eigendecomposition (+eig on %cplx).

Generates complex Hermitian test matrices and their real reference spectra
(numpy.linalg.eigvalsh), then prints a /tests/lib/saloon-eigh.hoon whose cases
check sort(computed eigenvalues) == sort(eigh eigenvalues).

A %cplx matrix is emitted as an ndray of packed atoms: each element is one
complexN_t slot, real component in the low half, imag in the high half (little
-endian) -- matching /lib/complex.  @cs = 2x@rs (64-bit, bloq 6); @cd = 2x@rd
(128-bit, bloq 7).  Eigenvalues are real, emitted as the matching real width
(@rs for cs, @rd for cd).
"""

import struct

import numpy as np


def f32_bits(x):
    return struct.unpack("<I", struct.pack("<f", float(x)))[0]


def f64_bits(x):
    return struct.unpack("<Q", struct.pack("<d", float(x)))[0]


def hoon_hex(v):
    """Dot-grouped Hoon hex atom (groups of 4 from the right, no leading zero)."""
    if v == 0:
        return "0x0"
    h = f"{v:x}"
    groups = []
    while len(h) > 4:
        groups.insert(0, h[-4:])
        h = h[:-4]
    groups.insert(0, h)
    return "0x" + ".".join(groups)


def cs_atom(z):
    # canonicalize -0.0 -> +0.0 so conjugate pairs are bit-exact Hermitian
    return hoon_hex(f32_bits(z.real + 0.0) | (f32_bits(z.imag + 0.0) << 32))


def cd_atom(z):
    return hoon_hex(f64_bits(z.real + 0.0) | (f64_bits(z.imag + 0.0) << 64))


def rs_lit(x):
    return ".0" if float(x) == 0.0 else f".{repr(float(x))}"


def rd_lit(x):
    return ".~0" if float(x) == 0.0 else f".~{_exp(repr(float(x)))}"


def _exp(s):
    if "e" not in s:
        return s
    m, e = s.split("e")
    sign = "-" if e[0] == "-" else ""
    e = e.lstrip("+-").lstrip("0") or "0"
    return f"{m}e{sign}{e}"


def cmatrix(mat, atom):
    rows = ["~[" + " ".join(atom(v) for v in row) + "]" for row in mat]
    return "~[" + " ".join(rows) + "]"


def rlist(vec, lit):
    return "~[" + " ".join(lit(v) for v in vec) + "]"


def hermitian(seed, n):
    rng = np.random.default_rng(seed)
    m = rng.standard_normal((n, n)) + 1j * rng.standard_normal((n, n))
    return (m + m.conj().T) / 2


# (name, matrix, complex-bloq, atom-fn, real-bloq, real-lit-fn)
CASES = [
    ("cs2", np.array([[2, 1j], [-1j, 2]], dtype=complex), 6, cs_atom, 5, rs_lit),
    ("cs3", hermitian(0, 3), 6, cs_atom, 5, rs_lit),
    ("cs4", hermitian(1, 4), 6, cs_atom, 5, rs_lit),
    ("cd3", hermitian(2, 3), 7, cd_atom, 6, rd_lit),
    ("cd4", hermitian(3, 4), 7, cd_atom, 6, rd_lit),
]


def emit():
    print("::  Tests for Saloon HERMITIAN eigendecomposition (+eig on %cplx).")
    print("::")
    print("::  GENERATED by saloon/tools/eigh_check.py -- do not edit by hand.")
    print("::  Per matrix: sort(computed real eigenvalues) = sort(eigh).")
    print("::  @cs (bloq 6) uses single-precision components, so a looser tol;")
    print("::  @cd (bloq 7) uses double.  Oracle: numpy.linalg.eigvalsh.")
    print("::")
    print("/-  ls=lagoon")
    print("/+  *test, *saloon, *lagoon")
    print("|%")
    print("::  cs single-precision saloon (rtol must be @rs-width); cd double.")
    print("++  scs  (sake %n .1e-6)")
    print("++  scd  (sake %n .~1e-12)")
    print("++  closes")
    print("  |=  [x=ray:ls y=ray:ls]")
    print("  ^-  ?")
    print("  (all:(lake %n) (is-close:(lake %n) x y [.1e-4 .1e-4]))")
    print("++  closed")
    print("  |=  [x=ray:ls y=ray:ls]")
    print("  ^-  ?")
    print("  (all:(lake %n) (is-close:(lake %n) x y [.~1e-9 .~1e-9]))")
    print("++  sortr")
    print("  |=  [r=ray:ls n=@ b=@]")
    print("  ^-  ray:ls")
    print("  =/  lst=(list @)")
    print("    =/  i  0")
    print("    =/  acc=(list @)  ~")
    print("    |-  ^-  (list @)")
    print("    ?:  =(i n)  (flop acc)")
    print("    $(i +(i), acc [(get-item:(lake %n) r ~[i]) acc])")
    print("  =/  cmp")
    print("    ?:  =(6 b)  |=([p=@ q=@] (~(lth rd:math [%n .~1e-10]) p q))")
    print("    |=([p=@ q=@] (~(lth rs:math [%n .1e-6]) p q))")
    print("  (en-ray:(lake %n) [[~[n] b %i754 ~] (sort lst cmp)])")
    for name, mat, cb, atom, rb, lit in CASES:
        n = mat.shape[0]
        w = np.sort(np.linalg.eigvalsh(mat))
        door = "scs" if cb == 6 else "scd"
        clo = "closes" if cb == 6 else "closed"
        print(f"::  {name}: {n}x{n} Hermitian, eigenvalues {[round(float(v),5) for v in w]}")
        print(f"++  m-{name}")
        print(f"  ^-  ray:ls")
        print(f"  (en-ray:(lake %n) [[~[{n} {n}] {cb} %cplx ~] {cmatrix(mat, atom)}])")
        print(f"++  w-{name}")
        print(f"  ^-  ray:ls")
        print(f"  (en-ray:(lake %n) [[~[{n}] {rb} %i754 ~] {rlist(w, lit)}])")
        print(f"++  test-{name}")
        print(f"  %-  expect")
        print(f"  !>  ({clo} (sortr (eigvals:{door} m-{name}) {n} {rb}) w-{name})")
    print("--")


if __name__ == "__main__":
    emit()
